repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        description: Uses 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
        entry: git-hook/helm-docs
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        language: script
        require_serial: true
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./templates

          # Repeating the flag adds this to the list, now [./templates, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl