repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        description: Uses 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file, and inserts the result into a corresponding 'README.md' file.
        entry: git-hook/helm-docs
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        language: script
        require_serial: true
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts